### PR TITLE
Fixed all eslint problems

### PR DESCRIPTION
**Pull request by Atuii**
eShrug

### CODE REVIEW

**Comment by Atuii** [comment]
Sorry wrong repo, closing

**Comment by nelsonic** [comment]
@Atuii what is the "_right_" repo...? 💭

**Comment by eritikass** [comment]
> @Atuii what is the "right" repo...? 💭

https://github.com/eritikass/learn-nightwatch

@nelsonic - used your repo in [Tallinna Polütehnikum](https://www.tptlive.ee/) as study material for software testing course...

**Comment by nelsonic** [comment]
@eritikass thanks for the _enlightenment_! 💡 
I was _wondering_ what all those "hits" were ... 😉 
glad it's _useful_ to _someone_! ❤️

**Pull request closed without merging**
